name       : texstudio
version    : 4.4.1
release    : 29
source     :
    - https://github.com/texstudio-org/texstudio/archive/refs/tags/4.4.1.tar.gz : 83c46c971081c053a01a186b4a7fbb492d75bef4070ff8fa045311eda186562b
homepage   : http://www.texstudio.org/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
summary    : Environment for creating LaTeX documents
component  : editor
description: |
    TeXstudio is an integrated writing environment for creating LaTeX documents. TeXstudio has numerous features like syntax-highlighting, integrated viewer, reference checking and various assistants.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(hunspell)
    - pkgconfig(poppler-qt5)
    - pkgconfig(x11-xcb)
    - quazip-devel
rundeps    :
    - texlive
setup      : |
    %cmake -DTEXSTUDIO_ENABLE_CRASH_HANDLER=OFF -Wno-dev
    %make
install    : |
    %make_install

    # Fix icons so they're usable
    for size in 16 22 32 48 64 128; do
        install -Dm00644 utilities/texstudio${size}x${size}.png \
        $installdir/usr/share/icons/hicolor/${size}x${size}/apps/texstudio.png
    done
    rm $installdir/usr/share/texstudio/{AUTHORS,CHANGELOG.txt,COPYING}
