name       : texstudio
version    : 2.11.0
release    : 1
source     :
    - http://jaist.dl.sourceforge.net/project/texstudio/texstudio/TeXstudio%202.11.0/texstudio-2.11.0.tar.gz : 170e6d68952251e8c64589b0d147cb7692005e135cc6fc14579c6fd593f54307
license    : GPL-2.0
summary    : Environment for creating LaTeX documents
component  : editor
description: |
    TeXstudio is an integrated writing environment for creating LaTeX documents. TeXstudio has numerous features like syntax-highlighting, integrated viewer, reference checking and various assistants.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11-xcb)
    - quazip-devel
rundeps    :
    - texlive
setup      : |
    qmake USE_SYSTEM_HUNSPELL=yes \
        USE_SYSTEM_QUAZIP=please \
        texstudio.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir