name       : texstudio
version    : 4.3.1
release    : 28
source     :
    - https://github.com/texstudio-org/texstudio/archive/4.3.1.tar.gz : 30fa3d4718ce793e4fe5c0c1a3d7d022cb63acc05272cfc0cd820848bcf48b00
homepage   : http://www.texstudio.org/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
summary    : Environment for creating LaTeX documents
component  : editor
description: |
    TeXstudio is an integrated writing environment for creating LaTeX documents. TeXstudio has numerous features like syntax-highlighting, integrated viewer, reference checking and various assistants.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(hunspell)
    - pkgconfig(poppler-qt5)
    - pkgconfig(x11-xcb)
    - quazip-devel
rundeps    :
    - texlive
setup      : |
    %qmake USE_SYSTEM_HUNSPELL=yes \
           USE_SYSTEM_QUAZIP=please \
           texstudio.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir

    # Fix icons so they're usable
    for size in 16 22 32 48 64 128; do
        install -D -m 00644 utilities/texstudio${size}x${size}.png $installdir/usr/share/icons/hicolor/${size}x${size}/apps/texstudio.png
    done
    rm $installdir/usr/share/texstudio/{AUTHORS,CHANGELOG.txt,COPYING,texstudio*.png}
