name       : texstudio
version    : 2.11.2
release    : 3
source     :
    - http://netix.dl.sourceforge.net/project/texstudio/texstudio/TeXstudio%202.11.2/texstudio-2.11.2.tar.gz : 02fdd4d1552593ba6ee85965f8043272230fa053b5b8e148405e80547c51d2dc
license    : GPL-2.0
summary    : Environment for creating LaTeX documents
component  : editor
description: |
    TeXstudio is an integrated writing environment for creating LaTeX documents. TeXstudio has numerous features like syntax-highlighting, integrated viewer, reference checking and various assistants.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11-xcb)
    - quazip-devel
rundeps    :
    - texlive
setup      : |
    qmake USE_SYSTEM_HUNSPELL=yes \
        USE_SYSTEM_QUAZIP=please \
        texstudio.pro
build      : |
    %make
install    : |-
    %make_install INSTALL_ROOT=$installdir
