name       : texstudio
version    : 2.12.6
release    : 8
source     :
    - https://jaist.dl.sourceforge.net/project/texstudio/texstudio/TeXstudio%202.12.6/texstudio-2.12.6.tar.gz : cdae8c9f3fa84af2424cfef6d4a3abb2437cc71ecb24c1883e4ecca2f2693da3
license    : GPL-2.0
summary    : Environment for creating LaTeX documents
component  : editor
description: |
    TeXstudio is an integrated writing environment for creating LaTeX documents. TeXstudio has numerous features like syntax-highlighting, integrated viewer, reference checking and various assistants.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(x11-xcb)
    - quazip-devel
rundeps    :
    - qt5-svg
    - texlive
setup      : |
    %qmake USE_SYSTEM_HUNSPELL=yes \
        USE_SYSTEM_QUAZIP=please \
        texstudio.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
